Add authentication for requests
pyronear/pyro-app pull request #2
Opened 2023-11-24 13:35 UTC by camcamBoir

#Description
- requête de login pour récupérer le token d'authentification
- création d'un service auth pour stocker et aller chercher le token d'authentification dans le AsyncStorage
- création de la configuration par défaut de axios pour toutes les requêtes

2023-11-25 21:59 UTC, aumeunier requested changes
Ton code est très bien, il faudrait cependant avoir toute la couche d'appels APIs dans les services, plutôt que de mettre la logique dans l'App.tsx / index.js

2023-11-25 21:59 UTC, aumeunier commented on package.json
> +    "axios": "^1.6.2"
Visiblement, vous avez nesté le PyroApp dans un dossier à l'intérieur du repository. Et tu as essayé de faire un npm install dans le dossier principal, d'où un package.json nouveau et quasi vide

2023-11-25 21:59 UTC, aumeunier commented on PyroApp/services/auth.service.ts
> +export const authService = {
Techniquement, ton "auth service" est plus un "storage service". Je garderais ça comme ça, mais sans exporter les fonctions de getToken. En soit, tu n'as pas besoin de les exposer si tu mets les vraies fonctions d'authentification dans ce fichier (au lieu du App.tsx)

2023-11-25 21:59 UTC, aumeunier commented on PyroApp/ios/Podfile.lock
> +  - "RNCAsyncStorage (from `../node_modules/@react-native-async-storage/async-storage`)"
je ne connais pas bien le Podfile.lock, mais le format est un peu étrange par rapport aux autres

2023-11-25 21:59 UTC, aumeunier commented on PyroApp/index.js
> +axios.interceptors.request.use(
très bien tes interceptor. 
En revanche, tout ce qui concerne axios devrait être dans un service. 
Je te conseillerais de créer un "apiClient.service.ts" ou quelque chose dans ce genre, et d'y mettre toute ta config axios. Petit conseil aussi : tu modifies le client axios pour tout ici. J'aurais tendance à plutôt créer une instance et l'exposer, pour qu'elle soit utilisée dans les autres services (notamment auth.service)

2023-11-25 21:59 UTC, aumeunier commented on PyroApp/App.tsx
> +  axios
à migrer dans un service (alerts.service.ts ?)

2023-11-25 21:59 UTC, aumeunier commented on PyroApp/App.tsx
> +    axios
à migrer dans le auth.service.ts

2023-11-25 22:00 UTC, aumeunier commented on PyroApp/ios/Podfile.lock
> +  - "RNCAsyncStorage (from `../node_modules/@react-native-async-storage/async-storage`)"
Petit commentaire aussi : je ne suis pas certain qu'ajouter des libs directement dans l'app iOS soit la bonne chose à faire

2023-11-27 20:22 UTC, camcamBoir commented on PyroApp/ios/Podfile.lock
> +  - "RNCAsyncStorage (from `../node_modules/@react-native-async-storage/async-storage`)"
j'ai suivi cette doc quand j'ai installé la lib (https://react-native-async-storage.github.io/async-storage/docs/install#install) et quand j'ai voulu link ensuite le module, ça m'a donné les changements sur le Podfile.lock donc je sais pas trop mais je dirais que c'est normal ?

2023-11-27 21:21 UTC, aumeunier approved these changes, later dismissed
Top @camcamBoir  ! Quelques commentaires, histoire de ;)

2023-11-27 21:21 UTC, aumeunier commented on PyroApp/App.tsx
> +    })();
Nice. Pour aller encore plus loin (et faire mon relou ;)) 
Le but du async / await est de permettre d'attendre la récupération d'un appel asynchrone pour utiliser la réponse ultérieurement. Ici, tu as pour effet de bord (principe du useEffect) de déclencher une étape de login pour récupérer le token. En soit, tu n'as pas forcément besoin de récupérer la réponse. Tu n'as donc pas besoin du async await. 

```
useEffect(() => {
authService.login();
}, []);
```


En revanche, tu ferais exactement ce que tu viens de faire si tu utilisais la réponse de l'appel login pour en faire quelque chose dans ce composant

2023-11-27 21:21 UTC, aumeunier commented on PyroApp/services/alerts.service.ts
> +      console.log(response.data[0]);
Je te conseille d'ajouter un if sur la longueur de la donnée, pour éviter un crash si il n'y a aucune alerte

2023-11-27 21:21 UTC, aumeunier commented on PyroApp/services/auth.service.ts
> +        password: '&Fib7!Eoc!LSfMpa',
Pas très grave à ce stade, mais à savoir qu'à partir du moment où tu as commit un password, il faut normalement le modifier car cela peut rester dans l'historique.
Je te conseille de regarder la lib dotenv pour gérer des variables d'environnement facilement https://www.npmjs.com/package/dotenv

2023-11-27 21:23 UTC, aumeunier commented on PyroApp/yarn.lock
Petite remarque également : je vois que tu as un package-lock.json ET un yarn.lock
Je n'ai pas de grosse préférence entre yarn et npm, mais il vaut mieux choisir entre les deux :)

2023-11-28 08:07 UTC, camcamBoir commented on PyroApp/services/auth.service.ts
> +        password: '&Fib7!Eoc!LSfMpa',
oups oui effectivement

2023-11-28 08:43 UTC, camcamBoir commented on PyroApp/yarn.lock
ce sera npm du coup :)

2023-11-28 08:52 UTC, camcamBoir commented on PyroApp/services/auth.service.ts
> +        password: '&Fib7!Eoc!LSfMpa',
je vais demander à mateo de le changer

2023-12-14 10:37 UTC, aumeunier approved these changes

2023-12-14 12:32 UTC, merged